### ISSUE TITLE
change SCD30 for diffrent sensor

### ISSUE THREAD

**Issue by smalecki** [ihewitt/VO2max#2]
Co2 sensor SCD30 have not enough range. 40000 ppm is 4%. During exhale without exercise we have about 3-4%. During exercise is more than 4%. 
Don't found replacement for that for now.

**Comment by ihewitt** [comment]
yeah although the CO2 sensor isn't crucial to getting the VO2 max calculation and is just providing some additional resp data. Also I think it improves the calculation since it can be used to provide the values for the respired air temperature and humidity. (although obviously these aren't wildly variable and probably doesn't improve much over having hardcoded defaults)
and as you say I also didn't see any suitable replacement either.

**Comment by ihewitt** [comment]
Thanks, yeah I can't see anything small enough or cheap enough to make sense anywhere. 
(finally got around to taking a look at this again! 🙂)

**Comment by ihewitt** [comment]
FYI switched to a ENS160 (with AN41) to test and it no longer maxes out, but doesn't seem to give values high enough for the exhaled air.
I'll test a little more, but I don't think the CO2 sensor (either) is of much use really.

**Comment by ihewitt** [comment]
Ongoing - more co2 sensors on way, will update site with details after building/testing.

**Comment by ihewitt** [comment]
FYI I added some notes about using a different sensor here (and uploaded the code - https://github.com/ihewitt/VO2max/commit/3321b3691952aad3dd693bd3de983f4fc1948c81)
Notes - https://blog.ivor.org/2024/03/the-ongoing-vo2-max-saga.html
I'll add the details to this repo also.
